import type { Metadata } from "next";
import Image from 'next/image';
import "./globals.css";
import Layout from "@/components/Layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Layout>{children}</Layout>
    </html>
  );
}
